const { validationResult } = require("express-validator");
const Response = require("../models/Response");
const { dispatchForAccident } = require("../services/dispatchService");
const { createAccidentAndTriggerWorkflow } = require("../services/accidentWorkflowService");

exports.createFromDetectionEngine = async (req, res, next) => {
  try {
    const expectedKey = process.env.DETECTION_API_KEY;
    if (expectedKey && req.headers["x-detection-key"] !== expectedKey) {
      return res.status(401).json({ success: false, message: "Invalid detection key" });
    }

    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ success: false, errors: errors.array() });
    }

    const accident = await createAccidentAndTriggerWorkflow({
      payload: req.body,
      source: "external_engine",
    });

    res.status(201).json({ success: true, accident });
  } catch (error) {
    next(error);
  }
};

exports.getMyAccidents = async (req, res, next) => {
  try {
    const responses = await Response.find({ userId: req.user._id })
      .populate("accidentId")
      .sort({ createdAt: -1 })
      .lean();

    const history = responses.map((r) => ({
      responseId: r._id,
      responseType: r.responseType,
      autoGenerated: r.autoGenerated,
      createdAt: r.createdAt,
      accident: r.accidentId,
    }));

    res.json({ success: true, history });
  } catch (error) {
    next(error);
  }
};

exports.manualCreateAccident = async (req, res, next) => {
  try {
    const accident = await createAccidentAndTriggerWorkflow({
      payload: { ...req.body, confidenceScore: req.body.confidenceScore ?? 1 },
      source: "manual",
    });

    await dispatchForAccident({
      accidentId: accident._id,
      reason: "Manual dispatch created by admin",
      assignedBy: "admin",
    });

    res.status(201).json({ success: true, accident });
  } catch (error) {
    next(error);
  }
};
