const { validationResult } = require("express-validator");
const Response = require("../models/Response");
const Notification = require("../models/Notification");
const User = require("../models/User");
const ChatLog = require("../models/ChatLog");
const { stopSafetyTimer } = require("../services/timerService");
const { dispatchForAccident } = require("../services/dispatchService");
const { emitToRole, emitToUser } = require("../services/socketManager");

exports.submitResponse = async (req, res, next) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ success: false, errors: errors.array() });
    }

    const { accidentId, responseType, responseTimeMs } = req.body;

    const existing = await Response.findOne({ accidentId, userId: req.user._id });
    if (existing) {
      return res.status(409).json({ success: false, message: "Response already submitted" });
    }

    const response = await Response.create({
      accidentId,
      userId: req.user._id,
      responseType,
      responseTimeMs,
      autoGenerated: false,
    });

    await ChatLog.create({
      accidentId,
      userId: req.user._id,
      senderType: "user",
      message: responseType === "Help" ? "Need Help" : "I'm Safe",
      responseType,
    });

    stopSafetyTimer({ accidentId, userId: req.user._id });

    if (responseType === "Help") {
      const introLog = await ChatLog.create({
        accidentId,
        userId: req.user._id,
        senderType: "system",
        message: "Admin support chat opened. Tell us what happened and what help you need.",
        responseType: "Chat",
      });

      emitToUser(req.user._id, "chat:message", { message: introLog });
      emitToRole("admin", "chat:message", { message: introLog });
      emitToRole("super_admin", "chat:message", { message: introLog });

      await dispatchForAccident({
        accidentId,
        reason: "User explicitly requested help",
        assignedBy: "system",
      });
    }

    const admins = await User.find({ role: { $in: ["admin", "super_admin"] } }).select("_id");
    if (admins.length) {
      await Notification.insertMany(
        admins.map((u) => ({
          userId: u._id,
          accidentId,
          type: "SYSTEM",
          message: `User ${req.user.email} submitted response: ${responseType}`,
        }))
      );
    }

    emitToRole("admin", "response:received", { accidentId, userId: req.user._id, responseType });
    emitToRole("super_admin", "response:received", { accidentId, userId: req.user._id, responseType });

    res.status(201).json({ success: true, response });
  } catch (error) {
    next(error);
  }
};

exports.getMyResponses = async (req, res, next) => {
  try {
    const responses = await Response.find({ userId: req.user._id })
      .populate("accidentId")
      .sort({ createdAt: -1 });

    res.json({ success: true, responses });
  } catch (error) {
    next(error);
  }
};
